# Generated by Django 5.0.4 on 2025-05-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('tipo_uso', models.CharField(blank=True, max_length=50)),
                ('ubiacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='Activa', max_length=20)),
                ('departamento_responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('electrica', 'Eléctrica'), ('limpieza', 'Limpieza'), ('mobiliario', 'Mobiliario'), ('climatizacion', 'Climatización')], max_length=20)),
                ('nivel_urgencia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en curso', 'En curso'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], default='Abierta', max_length=15)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True)),
                ('empleado_aginado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeustoFixapp.empleado')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeustoFixapp.instalacion')),
            ],
        ),
    ]
