# Generated by Django 5.2 on 2025-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('tipo_uso', models.CharField(blank=True, max_length=50)),
                ('ubiacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='Activa', max_length=20)),
                ('departamento_responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
