# Generated by Django 5.0.4 on 2025-05-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustoFixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
