# Generated by Django 5.0.4 on 2025-06-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeustoFixapp', '0002_alter_incidencia_fecha_resolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacion',
            old_name='ubiacion',
            new_name='ubicacion',
        ),
    ]
