# Generated by Django 5.0.4 on 2025-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeustoFixapp', '0003_rename_ubiacion_instalacion_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='empleado_aginado',
            new_name='empleado_asignado',
        ),
    ]
